### ISSUE TITLE
Integración de los repositorios de cada componente utilizando git submodule

### ISSUE THREAD

**Issue by kilianpg** [Arquisoft/Inci_e3b#2]
Los repositorios a integrar son:

- Módulo de carga de usuarios: [Loader_e3b](https://github.com/Arquisoft/Loader_e3b).
- Módulo de consulta y gestión de agentes: [Agents_e3b](https://github.com/Arquisoft/Agents_e3b).
- Módulo de gestión y carga de incidencias: [InciManager_e3b](https://github.com/Arquisoft/InciManager_e3b).
- Módulo de análisis y cuadro de mandos: [InciDashboard_e3b](https://github.com/Arquisoft/InciDashboard_e3b).

Referencias:
- [Git Tools - Submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules)

**Comment by miguelms95** [comment]
Me pongo a ello de momento en un repositorio privado, si @labra nos da permisos para crear repositorios en Arquisoft lo creo de nuevo ahí, ya veremos.

Enlace del repositorio: [Inci_e3b_submodules](https://github.com/miguelms95/Inci_e3b_submodules)

**Comment by miguelms95** [comment]
Se hizo en https://github.com/miguelms95/Inci_e3b_submodules
